apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appServiceName }}
  annotations:
    metrics.dynatrace.com/port: "{{ .Values.containerPort }}"
    metrics.dynatrace.com/scrape: "true"
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
